### ISSUE TITLE
Illlegal instruction

### ISSUE THREAD

**Issue by ulloaa** [zhoux85/STAligner#15]
Hello, after installing we get the error message below:

`>>> import STAligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.8/site-packages/STAligner-1.0.0-py3.8.egg/STAligner/__init__.py", line 11, in <module>
    from .ST_utils import match_cluster_labels, Cal_Spatial_Net, Stats_Spatial_Net, mclust_R, ICP_align
  File ".local/lib/python3.8/site-packages/STAligner-1.0.0-py3.8.egg/STAligner/ST_utils.py", line 6, in <module>
    from .mnn_utils import create_dictionary_mnn
  File ".local/lib/python3.8/site-packages/STAligner-1.0.0-py3.8.egg/STAligner/mnn_utils.py", line 5, in <module>
    from annoy import AnnoyIndex
  File "STALIGNER/conda/envs/env_STAligner/lib/python3.8/site-packages/annoy/__init__.py", line 16, in <module>
    from .annoylib import Annoy as AnnoyIndex
ImportError: libpmix.so.2: cannot open shared object file: No such file or directory
`

however, after adding the path of libpmix.so.2 to `LD_LIBRARY_PATH` we get:

`>>> import STAligner
Illegal instruction (core dumped)
` 

Could you please provide guidance on how to troubleshoot the above?

Thanks!

**Comment by zhoux85** [comment]
Hi. Did you install PyG (PyTorch Geometric) successful? The installation of PyG is tricky, and will cause many errors.

Please refer the package version in https://github.com/zhoux85/STAligner/blob/master/requirement.txt
