### ISSUE TITLE
About How to save the adata_contact 

### ISSUE THREAD

**Issue by Sawakotx** [zhoux85/STAligner#26]
I have successfully run the following code `adata_concat = STAligner.train_STAligner(adata_concat, iter_comb = None, verbose=True, device=used_device, margin=1.0)`.
But, due to jupyter notebook can be unstable sometimes, I want to save the adata_contact timely and I ran
`adata_concat.write(f"/spatial/Visium_STAligner_{today}.h5ad")`
It caused some errors, and here's the details.
`Traceback (most recent call last): 
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 148, in write_not_implemented
    raise NotImplementedError(
NotImplementedError: Failed to write value for uns/edgeList, since a writer for type <class 'tuple'> has not been implemented yet.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/workshop/visium_STAligner.py", line 118, in <module> 
    adata_concat.write(f"/spatial/0.Visium_STAligner_{today}.h5ad") 
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1912, in write_h5ad
    _write_h5ad(
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 118, in write_h5ad
    write_attribute(f, "uns", adata.uns, dataset_kwargs=dataset_kwargs)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad 
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 294, in write_mapping 
    write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/home/miniconda3/envs/STAligner/lib/python3.8/site-packages/anndata/_io/utils.py", line 212, in func_wrapper
    raise type(e)(
NotImplementedError: Failed to write value for uns/edgeList, since a writer for type <class 'tuple'> has not been implemented yet.

Above error raised while writing key 'uns/edgeList' of <class 'h5py._hl.files.File'> from /.`

I'd like to ask how I should save data correctly.
Looking forward to your reply. I would appreciate it!

**Comment by t-a-m-i** [comment]
@Sawakotx running into the same issue! How did you end up solving it and which package versions are you using in your environment?

**Comment by zhoux85** [comment]
@Sawakotx @t-a-m-i Hi. You can delete the key 'uns/edgeList' before saving h5ad file.

`del adata_concat.uns['edgeList']`
